### ISSUE TITLE
ImageOptim hook autocorrects

### ISSUE THREAD

**Issue by deivid-rodriguez** [sds/overcommit#346]
I've noticed that the `ImageOptim` hook autocorrects.

I wouldn't expect this since it's the only hook I've seen that changes the repository state. Right?

**Comment by sds** [comment]
You would be correct, but it's the nature of the tool itself. It at least doesn't stage those corrections.

If `image_optim` provided a way to see if an image was optimizable without optimizing it, then this wouldn't be a problem.

I'm open to suggestions of how to deal with this, but at the time it was deemed "not a big deal" as the user could always `git checkout` the original images. What's nice about having it autocorrect is you get the warning and then you can promptly stage the changes to get the optimized image.

In regards to autocorrection in general, I'm not against it, it's just not supported in the general case yet (see #238).

**Comment by deivid-rodriguez** [comment]
@sds As you said, no big deal. But did the cope behave previously as one would expect (https://github.com/brigade/overcommit/commit/71b31bdd5522966fbb83b1202507f1df80c2aa9d)? Haven't tried it but from `image_optim`'s README, the non-bang version of `optimize_images` doesn't seem to change the source image.

**Comment by sds** [comment]
Ah, yes, the hook used to call the Ruby API directly. I switched it in 71b31bd to use the executable since I didn't want to have to install the `image_optim` gem just to test Overcommit. Unfortunately, there was no mechanism to check if an image was optimizable via the command line at the time without modifying it.

I'm definitely open to a pull request that fixes this to be non-destructive. One solution could be to copy the applicable files to a temporary directory and run `image_optim` against those, reporting any files that were modified. Another would be to submit an patch upstream to support non-destructive optimization checks.

**Comment by sds** [comment]
Closing this ticket due to age. Happy to merge a pull request if this is desired!
