### ISSUE TITLE
Post-checkout hook proposal: `rake db:migrate` when `structure.sql` changed

### ISSUE THREAD

**Issue by janpaul123** [sds/overcommit#360]
Super useful for Rails development!

**Comment by lencioni** [comment]
This would be pretty similar to our npm install hooks:

- https://github.com/brigade/overcommit/blob/master/lib/overcommit/hook/post_checkout/npm_install.rb
- https://github.com/brigade/overcommit/blob/master/lib/overcommit/hook/shared/npm_install.rb

Should it be available for other hooks, like post rewrite, post merge, and post commit?

**Comment by sds** [comment]
I am wary of hooks that automatically perform mutating actions on `post-checkout` (yes, Overcommit currently has hooks that do this, but that doesn't change my feeling about them). I think there are legitimate scenarios where you are in the middle of debugging an issue and you do not want the `db:migrate` task to be run every time you change `HEAD` or checkout a file. Having to remember to disable such a hook in those circumstances would be a pain. Perhaps I'm worried about an edge case, but I've personally jumped around changing `HEAD` while running `up`/`down` on individual migrations in order to figure out why something failed.

I _would_ be in favor of a hook that reminds you to run `rake db:migrate` when `db:structure.sql` has changed.

**Comment by lencioni** [comment]
I agree with @sds about hooks that perform mutating actions. This is why at Brigade I implemented hooks similar to the npm install ones here but instead of running it for you, it simply tells you to run it.

**Comment by janpaul123** [comment]
Agreed, reminders would be better, including for npm/bundler.

**Comment by Structon** [comment]
Please opt me out of this

Thank you

met vriendelijke groet, Stefan Leijen

**Comment by sds** [comment]
Closing this ticket due to age. Happy to merge a pull request if this is desired!
