### ISSUE TITLE
Possibility to define a custom global default file

### ISSUE THREAD

**Issue by spras** [sds/overcommit#533]
I don't find this in the doc, and nothing related in this issues.

I think it could be useful to be able to redefine the default configuration file, on a global setting (env var ?), in order to activate or customise some rules on every project.

Or having a global .overcommit.yml file (in user home)  which would be aggragated with the repo .overcommit.yml

**Comment by sds** [comment]
Hey @spras, thanks for the suggestion.

I used to be a hard "no" on this idea, as I wanted to guarantee that hook runs on any machine were the same. However, I'm starting to appreciate that for certain workflows, it would be really nice to be able to define some hooks that are global in scope for a given development environment.

There are some problems we would need to solve if we were to introduce this however:

* Ensure that the hook signing logic ignores hooks defined in this global configuration file (since those aren't under source control
* Ensure we warn users when their global configuration potentially interferes with the repo's configuration (as this could be a source of confusion otherwise). There's no point in using Overcommit if you can simply "override" the rules set forth in the repo's configuration, because then the moment someone else checks out code you wrote it will break

Where I see global configuration being useful is for personal workflow enhancements, like auto-generating a tags file with [`ctags`](https://github.com/brigade/overcommit/blob/master/lib/overcommit/hook/shared/index_tags.rb) in response to events like `post-checkout` etc.

Very open to a pull request that tackles this, but I do think it's important we not allow a user's "personal" preferences interfere with the desires specified in the repo's configuration. Would love to hear more examples of your use cases to help me understand what kind of challenges you're trying to solve.

**Comment by spras** [comment]
Hi @sds 

I was setting up overcommit in my team and on all our projects, then i was wondering this about commonly used rules like the message commit rules.

Now, we duplicated theses rules on each project and this is not a so big deal.

I agree with you, hooks must run the same on any machine.

Thank's for your answer, and thank's for overcommit :-) 

You can close this issue as you please.

**Comment by sds** [comment]
Ah, I see what you're asking. Yes, it would be great if Overcommit offered a way to share hooks via gems so that you could define a set of hooks that can be used across an organization and not have to update it in every repository.

I'm definitely open to this idea, it'll just take some work and careful thinking to get right.
