### ISSUE TITLE
Display live output during hook run

### ISSUE THREAD

**Issue by HarlemSquirrel** [sds/overcommit#583]
I would like to be able to see the progress of RSpec as it runs for my pre-push command. 

This is especially helpful since this is a long-running command. Setting `quite: false` does not seem to work.

**Comment by sds** [comment]
Hey @HarlemSquirrel, what your asking for requires some substantial re-thinking of the hook runner.

Since Overcommit runs hooks in parallel, it becomes challenging to interleave output of multiple hook runs, and how you make this readable is not an easy question.

Open to suggestions, but ultimately would want to see a pull request implementing a solution given the complexity. Thanks!

**Comment by HarlemSquirrel** [comment]
Hey @sds I'm happy to look into it more. For a first implementation, I'm thinking we could set the commands run in series instead of parallel when the option is set for `live_output`. For me, I would only want this for long-running commands like running an entire test suite which I run as a pre-push command with just one other (brakeman) so not running in parallel wouldn't be a big deal. 

Could you point me to where in the code output is suppressed or redirected?

Thanks!

**Comment by sds** [comment]
There isn't a straightforward answer to your question—I'll simply suggest that you start looking in the hook runner and see where it takes you: https://github.com/brigade/overcommit/blob/ec8795c976c2ee11d8ccb6890f3118c954252eff/lib/overcommit/hook_runner.rb#L162

**Comment by horiaradu** [comment]
I can try and submit a pull request for this.
