### ISSUE TITLE
Execute CustomScript only on modified files

### ISSUE THREAD

**Issue by dpinol** [sds/overcommit#659]
How can I execute CustomScript only on modified files? If possible, can you document it?

thanks!

**Comment by sds** [comment]
By `CustomScript` I'm assuming you're referring to [this section in the documentation](https://github.com/sds/overcommit#adding-existing-git-hooks). 

You would need to write your script to inspect modified files directly using the Git index. Determining whether a file is "modified" depends on the hook type (pre-commit, etc.), so there's no one answer.

Given traditional hooks are supported for the purposes of migration, Overcommit doesn't provide documentation since you are writing your own traditional Git hook, rather than an Overcommit one. You can find documentation on traditional [Git hooks here](https://git-scm.com/docs/githooks).

If you're going through the trouble of writing your own hook, would encourage you to write a proper Overcommit hook where you can get the list of modified files via [`applicable_files`](https://github.com/sds/overcommit/blob/202253d6d858ea2ce081d9d5c3bfcf17a9bc7355/lib/overcommit/hook/pre_commit/rubo_cop.rb#L17) instead of using a traditional Git hook, where you have to do that all from scratch.

Hope this clarifies.
