### ISSUE TITLE
RailsSchemaUpToDate fails on non-breaking changes to older migrations

### ISSUE THREAD

**Issue by thepeoplesbourgeois** [sds/overcommit#695]
Stumbled upon this when I was implementing a coworker's requested changes within a migration file that the branch in question had moved beyond.

**REPRODUCTION**
1. Create a base Rails migration
1. Add something innocuous to this file e.g., a `raise ActiveRecord::IrreversibleMigration` within `#down`
1. Create another migration
1. Run `rails db:migrate`
1. Go back and alter that `#down` to now be a reversible migration

**EXPECTED**

Overcommit allows the change to be committed

**ACTUAL**

`RailsSchemaUpToDate` fails, sometimes saying the migration you're committing changes to doesn't match the version of the schema, sometimes (quizzically) saying that you're adding a migration but haven't updated the schema file

**Comment by sds** [comment]
Thanks for the clear report! Would happily merge a pull request fixing this issue.

**Comment by thepeoplesbourgeois** [comment]
And I would happily make such a PR, supposing I knew how the broken thing is broken ^_^

**Comment by sds** [comment]
Closing due to age of this ticket. Will happily merge a pull request from anyone wanting to see this fixed. As I don't personally utilize this hook, I don't have much context on how it should work. This is best addressed by someone who relies on that functionality heavily so the correct solution can be provided. Thanks!
